# Generated by Django 5.2.7 on 2025-11-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echo',
            options={'ordering': ['-created_at']},
        ),
    ]
