# Generated by Django 5.2.7 on 2025-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wave',
            options={'ordering': ['-created_at']},
        ),
    ]
